forge 'http://forge.puppetlabs.com'

mod 'spantree/java7', '0.2.2'
mod 'elasticsearch/elasticsearch', '0.2.3'
mod 'spantree/groovy', :git => 'https://github.com/Spantree/puppet-groovy.git'
mod 'gini/gradle', :git => 'https://github.com/gini/puppet-gradle'
mod 'puphpet/nginx', :git => 'git://github.com/puphpet/puppet-nginx.git'
mod 'willdurand/nodejs', '1.5.1'
mod 'jproyo/git', '0.1.0'
