forge 'http://forge.puppetlabs.com'

mod 'java7', :git => 'https://github.com/Spantree/puppet-java7.git'
mod 'elasticsearch/elasticsearch', '0.2.3'
mod 'groovy', :git => 'https://github.com/Spantree/puppet-groovy.git'
mod 'gini/gradle', :git => 'https://github.com/gini/puppet-gradle'
mod 'nginx', :git => 'git://github.com/puphpet/puppet-nginx.git'
mod 'willdurand/nodejs', '1.5.1'
mod 'jproyo/git', '0.1.0'