FROM docker.elastic.co/kibana/kibana:5.5.1

MAINTAINER Spantree Technology Group, LLC <devops@spantree.net>

RUN kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.18/logtrail-5.5.1-0.1.18.zip
