FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.1

MAINTAINER Spantree Technology Group <devops@spantree.net>

RUN elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.1.0/elasticsearch-sql-5.5.1.0.zip
